name: Docker

on:
  push:
    branches:
      - main

concurrency:
  group: docker-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: "26.04"
  REGISTRY: "ghcr.io"
  UBUNTU_IMAGE: "axiphi/oakestra-vm-ubuntu"
  MESA_IMAGE: "axiphi/oakestra-vm-mesa"
  WOLF_IMAGE: "axiphi/oakestra-vm-wolf"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker
        uses: docker/setup-docker-action@v5
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Import multi-architecture Ubuntu cloud image
        working-directory: ./oakestra-vm-ubuntu
        run: ./import-raw.sh docker "${VERSION}" linux/amd64 linux/arm64

      - name: Build multi-architecture Ubuntu VM base image
        working-directory: ./oakestra-vm-ubuntu
        run: |
          docker build \
            --platform linux/amd64,linux/arm64 \
            --load \
            --tag "${UBUNTU_IMAGE}:${VERSION}" \
            --build-arg "VERSION=${VERSION}" \
            .

      - name: Build multi-architecture Mesa image
        working-directory: ./oakestra-vm-mesa
        run: |
          docker build \
            --platform linux/amd64,linux/arm64 \
            --load \
            --tag "${MESA_IMAGE}:${VERSION}" \
            --build-arg "VERSION=${VERSION}" \
            .

      - name: Build multi-architecture Wolf image
        working-directory: ./oakestra-vm-wolf
        run: |
          docker build \
            --platform linux/amd64,linux/arm64 \
            --load \
            --tag "${WOLF_IMAGE}:${VERSION}" \
            --build-arg "VERSION=${VERSION}" \
            .

      - name: Push multi-architecture images
        run: |
          docker tag "${MESA_IMAGE}:${VERSION}" "${REGISTRY}/${MESA_IMAGE}:${VERSION}"
          docker tag "${WOLF_IMAGE}:${VERSION}" "${REGISTRY}/${WOLF_IMAGE}:${VERSION}"
          docker push "${REGISTRY}/${MESA_IMAGE}:${VERSION}"
          docker push "${REGISTRY}/${WOLF_IMAGE}:${VERSION}"
